// lib/seo-keywords.ts
// -----------------------------------------------------------------------------
// Extended SEO / AI-search keyword taxonomy (background metadata only).
// Sourced from the curated "key words June 2026" list (cleaned); deduplicated.
// Appended to <meta name="keywords"> and the Organization/WebSite JSON-LD
// "keywords" property on every page. Not rendered as visible page content.
// Reputation-damaging BrokerCheck / "barred" text is intentionally excluded.
// -----------------------------------------------------------------------------

export const EXTENDED_SEO_KEYWORDS: string[] = [
  "Andy Altahawi",
  "Altahawi",
  "Andy",
  "#andy Altahawi",
  "@andy Altahawi",
  "NYSE direct listing",
  "NYSE",
  "IPO",
  "alternative NYSE listing",
  "NYSE direct listing requirements",
  "Advantages of listing on NYSE Companies",
  "direct NYSE listing",
  "NASDAQ direct listing",
  "NASDAQ",
  "alternative",
  "listing process",
  "NASDAQ direct listing requirements",
  "Advantages of listing on NASDAQ Companies",
  "with direct NASDAQ listing",
  "Direct listing",
  "Going public without an IPO",
  "Stock exchange direct listing",
  "Non-IPO listing",
  "Benefits of direct listing",
  "Direct listing companies",
  "Direct listing requirements",
  "Wall Street Journal",
  "the WSJ",
  "finance",
  "fintech",
  "Kiplinger Magazine-USA",
  "MarketWatch",
  "Financial Times",
  "investing",
  "Bloomberg",
  "Markets",
  "CNN",
  "Business Money",
  "CNBC",
  "financial",
  "Barron's Magazine",
  "Barron's",
  "Forbes",
  "Killer Startups",
  "entrepreneurs",
  "business endeavors",
  "Economist",
  "Fortune",
  "Investopedia",
  "investment",
  "market",
  "deal maker",
  "newcomers directly Listed",
  "Directly listed",
  "Entrepreneur",
  "Direct Exchange Listing",
  "Fast Company",
  "Motley Fool",
  "Inc",
  "Money",
  "Wefunder",
  "Republic",
  "SeedInvest",
  "StartEngine",
  "GoFundMe",
  "Fundly",
  "DonorsChoose",
  "Classy",
  "Financial Advisors",
  "NASDAQ LISTING ADVISOR",
  "listing consultant",
  "International Finance Magazine",
  "Financial Planning Magazine",
  "Global Banking And Finance",
  "1934 Act",
  "1933 Act",
  "506b",
  "506c",
  "Reg A+",
  "Reg D",
  "Reg S",
  "pipe",
  "Smart Investor",
  "New York Stock Exchange Direct Listing",
  "DPO",
  "SEC",
  "Money magazine",
  "Kiplinger",
  "The Economist",
  "securities and exchange commission",
  "amro Altahawi",
  "DPO. Regulation A+ platform",
  "Free regulation A listing",
  "regulation A offerings",
  "Reg A expert",
  "mini ipo",
  "Reg A offering",
  "Go public",
  "IPO listing",
  "IPO issue",
  "buy stocks",
  "Kickstarter",
  "IPO center",
  "direct DPO",
  "NASDAQ listing",
  "NYSE listing",
  "initial public offering",
  "an initial public offering",
  "latest ipo",
  "506 offering",
  "current ipo offerings",
  "business fundraising sites",
  "Razoo",
  "Indiegogo",
  "best ipo",
  "ipo offers",
  "Crowdrise",
  "reg yy",
  "start up",
  "crowdfunding. crowdfunding portal",
  "Crowdfunder",
  "Reg A crowdfunding",
  "Regulation A+ crowdfunding",
  "crowdfunding attorney",
  "crowdfunding lawyer",
  "title iii crowdfunding",
  "crowdfunding for individuals",
  "start crowdfunding",
  "crowdfunding organizations",
  "crowdfunding without fees",
  "top crowdfunding platforms",
  "raising money through crowdfunding",
  "crowdfunding campaign",
  "campaign crowdfunding",
  "top crowdfunding campaigns",
  "best crowdfunding campaigns",
  "crowdfunding campaign help",
  "best crowdfunding sites",
  "best crowdfunding sites for small business",
  "top 10 crowdfunding sites",
  "top 5 crowdfunding sites",
  "most popular crowdfunding sites 2017",
  "most successful crowdfunding sites",
  "list of crowdfunding sites",
  "2026",
  "2027",
  "2028",
  "2029",
  "2030",
  "2031",
  "2032",
  "2033",
  "2034",
  "2035",
  "2015 ipo calendar",
  "ipo 2015 calendar",
  "stock ipo calendar",
  "ipo calendar",
  "ipo calendar 2015",
  "new ipo calendar",
  "upcoming ipo calendar",
  "best money raising sites",
  "money raising sites",
  "site to raise money for projects",
  "sites to help raise money",
  "raise money for project",
  "raise funds for your project",
  "crowd raising websites",
  "website to raise money",
  "WallStreet journal",
  "S1",
  "S-1",
  "Reg D 506B",
  "Reg D506C",
  "Reg A offering platform",
  "Reg A+ Platform",
  "Reg A+ SEC",
  "filing",
  "Reg A+ attorney",
  "Reg A+ offering platform",
  "Reg A+ portal",
  "Reg A+ website",
  "reg a",
  "platform",
  "Reg A Platform",
  "Reg A tier 2",
  "Reg A+ tier 2",
  "regulation a",
  "regulation a offering",
  "Regulation A+",
  "Regulation A attorney",
  "Regulation A portal",
  "Regulation A+ offering platform",
  "Regulation A+ Platform",
  "Regulation A platform",
  "SEC attorney",
  "SEC lawyer",
  "website crowdfunding",
  "crowdfunding websites for small business",
  "popular crowdfunding websites",
  "international crowdfunding websites",
  "crowdfunding websites",
  "top crowdfunding websites",
  "Adamson Brothers",
  "IPOFLOW",
  "Investment banking",
  "Banking",
  "Tycon partners",
  "Going public",
  "expert",
  "Manhattan Street capital",
  "shell Raising Capital",
  "SPAC",
  "using a Regulation A+",
  "Mini-IPO SEC.gov",
  "Wikipedia",
  "A+ Offering",
  "JOBS Act",
  "WRH+Co",
  "Regulation A+ Offering",
  "Hype or Reality? Crowdfund",
  "Insider",
  "MOFO",
  "Jumpstarter",
  "Summarize Title IV",
  "New Reg A+",
  "Solution",
  "What Is Reg A",
  "What Startups",
  "Reg A+ equity",
  "How Regulation A+ Works",
  "Equity Crowdfunding",
  "Fund Athena",
  "Blank-check",
  "Blank Check",
  "Colonial Stock",
  "Securities",
  "Regulation",
  "We Found A Reg Infographic",
  "Title IV Reg A+",
  "Blog Regulation A+",
  "Securex Filings",
  "LLC",
  "coporation",
  "corporations",
  "crowdfund.co",
  "www.directlylisted.com",
  "Fundraise Reg A Offering",
  "The Securities and Exchange Commission",
  "CrowdExpert",
  "Testing the Waters",
  "Crowdfunding",
  "Regulation A+ SEC EquityNet",
  "reg a+ offerings regulation",
  "a+ Investopedia",
  "reg a+ offerings",
  "rules regulation",
  "a+ crowdfunding",
  "offering requirements regulation a+",
  "Investopedia reg a+",
  "companies regulation a+",
  "summary regulation a+",
  "real estate",
  "My Mini-IPO",
  "Company Goes Public",
  "Via Reg A+",
  "on OTCQX FundersClub",
  "enable Reg A+",
  "raises on the platform",
  "Securities Regulation s",
  "what is reg a+",
  "crowdfunding platforms",
  "ipo reg a+",
  "offerings regulation a+",
  "rules regulation s",
  "offering requirements",
  "SlideShare",
  "regulation a securities act of 1933",
  "jobs act 106",
  "reg a tier 2 offering",
  "text",
  "offering regulation",
  "a plus regulation",
  "SEC Approves",
  "New \"Reg A+\"",
  "Rules for Crowdfunding",
  "vs regulation d",
  "difference between reg a and reg d",
  "rule 506",
  "of regulation d",
  "506 B",
  "Regulation D",
  "Rule 506(b) vs Rule 506(c)",
  "series 7",
  "regulations",
  "Funded Resources",
  "on Regulation A+",
  "OTC Markets",
  "Tripoint",
  "FINRA Jumpstart",
  "Our Business Startups Jobs act",
  "Tycon",
  "approval",
  "SEC qualification",
  "Equity Investment",
  "Equity Venture",
  "Goldman Sachs",
  "Merrill Lynch",
  "Reg \"A\"",
  "security exchange commission",
  "Bank",
  "capital raise",
  "raise capital",
  "raising capital",
  "funding venture capital",
  "crowdsourced private equity",
  "convertible debt",
  "Circle Up",
  "Angel List",
  "Endurance Lending Network",
  "Somnolent Rocket Hub Grow",
  "Venture Community Micro",
  "Ventures Cash From the Crowd",
  "entrepreneur entrepreneurship",
  "investors",
  "money success",
  "tech companies",
  "energy companies",
  "angel funding",
  "angel investors",
  "biotech companies",
  "early-stage",
  "VC finra",
  "tech capital raise",
  "energy capital",
  "raise technology",
  "crowdfunding tech",
  "crowdfunding energy",
  "crowdfunding biotech",
  "capital investors",
  "debt crowdfunding",
  "convertible notes",
  "early stage",
  "finance early",
  "stage investing companies",
  "investment companies",
  "invest in companies",
  "investing basics",
  "how to invest raise investment",
  "deals seed stage",
  "crowdfunding campaigns capital",
  "raising campaigns",
  "accredited investors",
  "unaccredited investors",
  "offering investment",
  "offering equity",
  "offering startups",
  "startup equity",
  "net fundable",
  "title I",
  "title ii",
  "title iii",
  "title iv",
  "startup engine",
  "AngelList",
  "crowdfund",
  "Online Business",
  "Funding GoFundMe",
  "UBS Wealth",
  "Management",
  "Online Business Funding",
  "Micro ventures",
  "Equity Net",
  "cutting edge",
  "capital circle up",
  "roof stock",
  "funded",
  "national exchange listed",
  "stock market",
  "NASADAQ direct listing",
  "NASDAQ conventional listing",
  "NYSE exchange listing",
  "crowd seed investment",
  "seed investors",
  "seed company",
  "venture",
  "Corp .",
  "Facebook",
  "twitter",
  "LinkedIn",
  "synergy",
  "Initial public offerings",
  "profiles",
  "Registered Broker",
  "FINRA",
  "broker check",
  "Financial Industry Regulatory Authority",
  "Barron’s Magazine",
  "Barron’s",
  "Need to Know About Regulation A+",
  "What crowdfunding sites are offering Title IV",
  "‎ We Found A Reg‎ Infographic",
  "‎ The Securities and Exchange Commission",
  "Securities Regulations",
  "rules regulations",
  "New “Reg A+”",
  "Reg “A”",
  "VC early-stage real estate investments investing",
  "New York Stock exchange conventional listing",
  "Corp",
  "MarketWatch’s got it. 5. Due: A simple",
  "informative",
  "you can always find reliable financial information"
];
